              (in-package #:cl-user)                                  (defconstant                                  +size+ 512)  (defconstant
              +pad+ 2) (defparameter                                  +colors+                                      '("#453A62" "#5E5086"
              "#8F4E8B")) (defun                                      source-lines ()                               (unless *load-truename* (error
              "Missing source pathname."))                            (with-open-file                               (input *load-truename*
              :direction :input) (loop for                            line = (read-line                             input nil nil) while line
              collect line))) (defun inkp                             (character) (not                              (char= character #\Space)))
              (defun art-width (art) (reduce                          #'max art :key                                #'length)) (defun write-runs
              (stream art lower upper) (loop                          for line in art                               for row from 0 do (loop with
              column = lower while (and (<                             column upper) (<                             column (length line))) do (if
              (inkp (char line column)) (let                           ((start column))                             (loop while (and (< column
       upper) (< column (length                                        line)) (inkp (char                                  line column))) do (incf
       column)) (format stream                                                                                             "M~D ~D h~D v1 h-~D z" start
       row (- column start) (- column                                  start))) (incf                                      column))))) (defun write-svg
       (pathname art) (let* ((width                                    (art-width art))                                    (height (length art)) (side (+
       (max width height) (* 2                                         +pad+))) (offset-x                                  (floor (- side width) 2))
       (offset-y (floor (- side                                         height) 2)) (cuts                                  (list 0 (floor width 3) (floor
       (* 2 width) 3) width)))                                                                                             (ensure-directories-exist
       pathname) (with-open-file                                        (stream pathname                                   :direction :output :if-exists
       :supersede :if-does-not-exist                                    :create) (format                                   stream "<?xml version=~S "
       "1.0") (format stream                                            "encoding=~S?>~%"                                  "UTF-8") (format stream
"<svg xmlns=~S "                                                                                                                  "http://www.w3.org/2000/svg")
(format stream                                                                                                                    "width=~S height=~S " (format
nil "~D" +size+) (format nil                                             "~D" +size+))                                            (format stream
"viewBox=~S role=~S " (format                                            nil "0 0 ~D ~D"                                          side side) "img") (format
stream "aria-labelledby=~S "                                                                                                      "title description") (format
stream "shape-rendering=~S>~%"                                           "crispEdges")                                            (format stream "<title id=~S>"
"title") (format stream                                                  "closurelab logo")                                       (format stream "</title>~%")
(format stream "<desc id=~S>"                                            "description")                                           (format stream
"Mirrored Cs and ") (format                                              stream                                                   "a Greek lambda.") (format
stream "</desc>~%") (format                                               stream                                                  "<g transform=~S>~%" (format
nil "translate(~D ~D)"                                                    offset-x                                                offset-y)) (loop for color in
+colors+ for (lower upper) on                                             cuts while upper                                        do (format stream
"<path fill=~S d=~S/>~%" color                                                                                                    (with-output-to-string (path)
(write-runs path art lower                                                upper)))) (format                                       stream "</g>~%</svg>~%"))))
(defun render-png (svg png)                                                                                                       (ensure-directories-exist png)
(let ((process                                                            (sb-ext:run-program                                     "rsvg-convert" (list
"-b" "white" (format nil                                                  "--width=~D"                                           +size+) (format nil
"--height=~D" +size+) (format                                              nil "--output=~A"                                      (namestring png)) (namestring
svg)) :search t :output                                                   *standard-output*                                       :error *error-output* :wait
t))) (unless (zerop                                                                                                               (sb-ext:process-exit-code
process)) (error                                                                                                                  "PNG renderer failed: ~D"
(sb-ext:process-exit-code                                                process))))) (defun                                      as-directory (name) (when
(zerop (length name)) (error                                                                                                      "Empty output directory."))
(pathname (if (char= (char                                               name (1- (length                                         name))) #\/) name (concatenate
'string name "/")))) (defun                                             output-directory ()                                       (let ((arguments (cdr
sb-ext:*posix-argv*))) (when                                            (< 1 (length                                              arguments)) (error
"Too many arguments."))                                                 (as-directory (if                                         arguments (first arguments)
"build")))) (defun main ()                                             (let* ((art                                                (source-lines)) (directory
(output-directory)) (svg                                               (merge-pathnames                                           "closurelab-logo.svg"
directory)) (png                                                      (merge-pathnames                                            "closurelab-logo.png"
directory))) (write-svg svg                                           art) (render-png svg png)                                   (format t
"Wrote ~A~%Wrote ~A~%"                                                (namestring svg)                                            (namestring png)))) (main) #|.
..... ...... ...... ...... ...                                       ...... ...... ...... .....                                   . ...... ...... ...... ......
.. ...... ...... ...... ......                                       ... ...... ...... ...... .                                   ..... ...... ...... ...... ...
...... ...... ...... ...... ..                                        ...... ...... ...... ....                                   .. ...... ...... ...... ......
... ...... ...... ...... .....                                      ..... ...... ...... ......                                    ...... ...... ...... ...... ..
 ...... ...... ...... ...... .                                      .. ...... ...... ...... ...                                   ... ...... ...... ...... .....
.... ...... ...... ...... ....                                      ...... ...... ...... ......                                    ...... ...... ...... ...... .
. ...... ...... ...... ......                                      .... ...... ...... ...... ...                                  .... ...... ...... ...... ....
..... ...... ...... ...... ...                                     . ...... ...... ...... ......                                  . ...... ...... ...... ......
.. ...... ...... ...... ......                                     ..... ...... ...... ...... ..                                  ..... ...... ...... ...... ...
...... ...... ...... ...... ..                                    ... ...... ...... ...... .....                                  .. ...... ...... ...... ......
... ...... ...... ...... .....                                     ...... ...... ...... ...... .                                  ...... ...... ...... ...... ..
 ...... ...... ...... ...... .                                   ..... ...... ...... ...... ....                                  ... ...... ...... ...... .....
.... ...... ...... ...... ....                                   .. ...... ...... ...... ...... .                                  ...... ...... ...... ...... .
. ...... ...... ...... ......                                    ...... ...... ...... ...... ....                                 .... ...... ...... ...... ....
..... ...... ...... ...... ...                                  .... ...... ...... ...... ......                                  . ...... ...... ...... ......
.. ...... ...... ...... ......                                  . ...... ...... ...... ...... ...                                 ..... ...... ...... ...... ...
...... ...... ...... ...... ..                                  ..... ...... ...... ...... ......                                 .. ...... ...... ...... ......
... ...... ...... ...... .....                                 ... ...... ...... ...... ...... ..                                 ...... ...... ...... ...... ..
 ...... ...... ...... ...... .                                  ...... ...... ...... ...... .....                                 ... ...... ...... ...... .....
.... ...... ...... ...... ....                                 .... ...... ...... ...... ...... ..                                 ...... ...... ...... ...... .
. ...... ...... ...... ......                                 .. ...... ...... ...... ...... .....                                .... ...... ...... ...... ....
..... ...... ...... ...... ...                                ...... ...... ...... ...... ...... .                                . ...... ...... ...... ......
.. ...... ...... ...... ......                               .... ...... ...... ...... ...... ....                                ..... ...... ...... ...... ...
...... ...... ...... ...... ..                               . ...... ...... .. ... ...... ......                                 .. ...... ...... ...... ......
... ...... ...... ...... .....                               ..... ...... .....  ...... ...... ...                                ...... ...... ...... ...... ..
 ...... ...... ...... ...... .                              ... ...... ......   .... ...... ......                                ... ...... ...... ...... .....
.... ...... ...... ...... ....                               ...... ...... ...    ...... ...... ...                                ...... ...... ...... ...... .
. ...... ...... ...... ......                               .... ...... ......   .... ...... ......                               .... ...... ...... ...... ....
       ..... ...... ...... ...... ...                      .. ...... ...... .    . ...... ...... ..                        . ...... ...... ...... ......
       .. ...... ...... ...... ......                      ...... ...... ....    ..... ...... .....                        ..... ...... ...... ...... ...
       ...... ...... ...... ...... ..                      ... ...... ......     .. ...... ...... .                        .. ...... ...... ...... ......
       ... ...... ...... ...... .....                     . ...... ...... ..     ...... ...... ....                        ...... ...... ...... ...... ..
        ...... ...... ...... ...... .                     ..... ...... .....     ... ...... ......                         ... ...... ...... ...... .....
       .... ...... ...... ...... ....                     .. ...... ...... .      ...... ...... ....                        ...... ...... ...... ...... .
       . ...... ...... ...... ......                      ...... ...... ...       ... ...... ......                        .... ...... ...... ...... ....
       ..... ...... ...... ...... ...                    .... ...... ......        ...... ...... ...                       . ...... ...... ...... ......
       .. ...... ...... ...... ......                   .. ...... ...... .        .... ...... ......                       ..... ...... ...... ...... ...
       ...... ...... ...... ...... ..                   ...... ...... ....        . ...... ...... ..                       .. ...... ...... ...... ......
              ... ...... ...... ...... .....            ... ...... ......         ..... ...... .....                ...... ...... ...... ...... ..
               ...... ...... ...... ...... .           . ...... ...... ..         .. ...... ...... .                ... ...... ...... ...... .....
              .... ...... ...... ...... ....           ..... ...... .....          ..... ...... .....                ...... ...... ...... ...... .
              . ...... ...... ...... ......            .. ...... ...... .          .. ...... ...... .               .... ...... ...... ...... ....
              ..... ...... ...... ...... ...           ...... ...... ...           ...... ...... ....               . ...... ...... ...... ......
              .. ...... ...... ...... ......          .... ...... ......           ... ...... ......                ..... ...... ...... ...... ...
              ...... ...... ...... ...... ..          . ...... ...... ..            ...... ...... ...               .. ...... ...... ...... ......
              ... ...... ...... ...... .....         ...... ...... ....            .... ...... ......               ...... ...... ...... ...... ..
               ...... ...... ...... ...... .         ... ...... ......             . ...... ...... ..               ... ...... ...... ...... .....
              .... ...... ...... ...... ....        . ...... ...... ..              .... ...... ......               ...... ...... ...... ......|#
